'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useState} from 'react';
import {assetPath} from './assetPath';
import {useI18n, type Language} from '@/lib/i18n';
const links=[['Research','/research'],['Projects','/projects'],['People','/people'],['Collaborate','/collaborate'],['About','/about']];
function LanguageSelect({compact=false}:{compact?:boolean}){const {lang,setLang,t}=useI18n();return <label className="flex items-center gap-2 text-xs text-slate-300"><span className={compact?'':'sr-only'}>{t('Language')}</span><select value={lang} onChange={e=>setLang(e.target.value as Language)} aria-label={t('Language')} className="h-11 min-w-[92px] rounded-sm bg-navy border border-white/30 text-white px-2 focus:outline-none focus:ring-2 focus:ring-cyan"><option value="en">English</option><option value="zh">中文</option><option value="fr">Français</option></select></label>}
export default function Header(){const {t}=useI18n();const path=usePathname();const [open,setOpen]=useState(false);return <header className="bg-navy text-white border-b border-white/10 sticky top-0 z-50"><div className="container-lab flex items-center justify-between min-h-[76px] gap-3"><Link href="/" className="flex items-center gap-2 min-w-0" aria-label="ZHIXING Space Lab home"><span className="bg-white rounded-sm w-11 h-11 md:w-14 md:h-14 shrink-0 flex items-center justify-center overflow-hidden"><img src={assetPath('zhixing-en.webp')} alt="" className="w-full h-full object-contain"/></span><span className="font-display font-bold tracking-tight text-base md:text-lg leading-tight truncate">ZHIXING <span className="text-cyan">知行</span><small className="hidden sm:block text-[10px] uppercase tracking-[.12em] text-slate-400 font-sans font-medium">{t('Space Lab · Research initiative')}</small></span></Link><div className="hidden lg:flex items-center gap-5 lg:gap-8"><nav className="flex gap-4 lg:gap-7 text-sm">{links.map(([name,url])=><Link key={url} className={path.startsWith(url)?'text-cyan':'text-slate-300 hover:text-white'} href={url}>{t(name)}</Link>)}</nav><LanguageSelect/></div><button className="lg:hidden border border-white/30 px-3 h-11" aria-expanded={open} aria-label={t('Menu')} onClick={()=>setOpen(!open)}>{t('Menu')}</button></div><div className="lg:hidden container-lab border-t border-white/10 py-2"><LanguageSelect compact/></div>{open&&<nav className="lg:hidden container-lab pb-5 flex flex-col gap-1">{links.map(([name,url])=><Link className="py-2" key={url} href={url} onClick={()=>setOpen(false)}>{t(name)}</Link>)}</nav>}</header>}
